"""inventory > product delete cascade

Revision ID: 18de19f55dc4
Revises: e5679bce36f6
Create Date: 2024-08-10 01:27:16.268284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18de19f55dc4'
down_revision: Union[str, None] = 'e5679bce36f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
