"""companies > contact nullable field

Revision ID: a0ac706e43dc
Revises: fb9b21ef03e8
Create Date: 2024-07-28 11:35:05.667136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ac706e43dc'
down_revision: Union[str, None] = 'fb9b21ef03e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'alt_contact_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'alt_contact_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
