"""many2many relation warehouse cylic_counts

Revision ID: e5679bce36f6
Revises: a0ac706e43dc
Create Date: 2024-07-30 16:43:41.601277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5679bce36f6'
down_revision: Union[str, None] = 'a0ac706e43dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    op.create_table('warehouse_ccount_table',
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cyclic_count_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cyclic_count_id'], ['cyclic_count.id'], name='warehouse_ccount_table_ccount_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name='warehouse_ccount_table_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('warehouse_id', 'cyclic_count_id', name='warehouse_ccount_table_pkey')
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('warehouse_ccount_table')
    # ### end Alembic commands ###
